/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CallRecordsRouteImport } from './routes/call-records'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as VoiceAgentRouteImport } from './routes/voice-agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRecordsRoute = CallRecordsRouteImport.update({
  id: '/call-records',
  path: '/call-records',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAgentRoute = VoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/call-records': typeof CallRecordsRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/voice-agent': typeof VoiceAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/call-records': typeof CallRecordsRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/voice-agent': typeof VoiceAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/call-records': typeof CallRecordsRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/voice-agent': typeof VoiceAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/call-records'
    | '/dashboard'
    | '/knowledge-base'
    | '/voice-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/call-records'
    | '/dashboard'
    | '/knowledge-base'
    | '/voice-agent'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/call-records'
    | '/dashboard'
    | '/knowledge-base'
    | '/voice-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CallRecordsRoute: typeof CallRecordsRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  VoiceAgentRoute: typeof VoiceAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-records': {
      id: '/call-records'
      path: '/call-records'
      fullPath: '/call-records'
      preLoaderRoute: typeof CallRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-agent': {
      id: '/voice-agent'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof VoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  CallRecordsRoute: CallRecordsRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  VoiceAgentRoute: VoiceAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
